import { Project } from './types';

export const sampleProjects: Project[] = [
  {
    id: '1',
    name: 'Austin 24-Unit Community',
    location: { city: 'Austin', state: 'TX', lat: 30.2672, lng: -97.7431 },
    stage: 'production',
    unitCount: 24,
    estimatedValue: 4800000,
    startDate: '2025-09-01',
    estimatedCompletion: '2026-06-15',
    contacts: [{ name: 'Sarah Chen', role: 'Developer', email: 'sarah@example.com' }],
    notes: 'Phase 1 of 3. Foundation complete, framing underway.',
    photos: [],
    tags: ['multi-family', 'phase-1'],
    priority: 'high',
    healthStatus: 'on-track',
    createdAt: '2025-08-15T00:00:00Z',
    updatedAt: '2026-02-28T00:00:00Z',
    history: [],
  },
  {
    id: '2',
    name: 'Denver Workforce Housing',
    location: { city: 'Denver', state: 'CO', lat: 39.7392, lng: -104.9903 },
    stage: 'permitting',
    unitCount: 18,
    estimatedValue: 3200000,
    startDate: '2026-01-15',
    estimatedCompletion: '2026-10-01',
    contacts: [{ name: 'Mike Rivera', role: 'Project Manager', email: 'mike@example.com' }],
    notes: 'Zoning approved. Waiting on building permits — expected 2-3 weeks.',
    photos: [],
    tags: ['workforce', 'affordable'],
    priority: 'high',
    healthStatus: 'at-risk',
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: '2026-02-25T00:00:00Z',
    history: [],
  },
  {
    id: '3',
    name: 'Fort Collins 12-Unit',
    location: { city: 'Fort Collins', state: 'CO', lat: 40.5853, lng: -105.0844 },
    stage: 'design',
    unitCount: 12,
    estimatedValue: 2400000,
    contacts: [{ name: 'Lisa Park', role: 'Architect', email: 'lisa@example.com' }],
    notes: 'Design review scheduled for next week. Client wants modern farmhouse aesthetic.',
    photos: [],
    tags: ['single-family', 'custom'],
    priority: 'medium',
    healthStatus: 'on-track',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
    history: [],
  },
  {
    id: '4',
    name: 'Boulder ADU Program',
    location: { city: 'Boulder', state: 'CO', lat: 40.015, lng: -105.2705 },
    stage: 'qualified',
    unitCount: 30,
    estimatedValue: 4500000,
    contacts: [{ name: 'James Wu', role: 'City Liaison', email: 'james@boulder.gov' }],
    notes: 'City partnership for ADU pilot. 30 units across 15 properties.',
    photos: [],
    tags: ['adu', 'municipal', 'pilot'],
    priority: 'medium',
    healthStatus: 'on-track',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-18T00:00:00Z',
    history: [],
  },
  {
    id: '5',
    name: 'Phoenix Senior Living',
    location: { city: 'Phoenix', state: 'AZ', lat: 33.4484, lng: -112.074 },
    stage: 'lead',
    unitCount: 40,
    estimatedValue: 8000000,
    contacts: [{ name: 'Tom Bradley', role: 'Investor', email: 'tom@seniorliving.com' }],
    notes: 'Initial inquiry from senior living developer. Meeting scheduled March 10.',
    photos: [],
    tags: ['senior', 'large-scale'],
    priority: 'low',
    healthStatus: 'on-track',
    createdAt: '2026-02-25T00:00:00Z',
    updatedAt: '2026-02-25T00:00:00Z',
    history: [],
  },
  {
    id: '6',
    name: 'Salt Lake City Mixed-Use',
    location: { city: 'Salt Lake City', state: 'UT', lat: 40.7608, lng: -111.891 },
    stage: 'lead',
    unitCount: 16,
    estimatedValue: 3600000,
    contacts: [{ name: 'Ana Gomez', role: 'Developer', email: 'ana@slcdev.com' }],
    notes: 'Interested in ground-floor retail + residential above. Need feasibility study.',
    photos: [],
    tags: ['mixed-use', 'urban'],
    priority: 'low',
    healthStatus: 'on-track',
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
    history: [],
  },
  {
    id: '7',
    name: 'Boise Starter Homes',
    location: { city: 'Boise', state: 'ID', lat: 43.615, lng: -116.2023 },
    stage: 'delivered',
    unitCount: 8,
    estimatedValue: 1600000,
    actualValue: 1720000,
    startDate: '2025-03-01',
    estimatedCompletion: '2025-12-01',
    actualCompletion: '2025-11-15',
    contacts: [{ name: 'Dave Kim', role: 'Buyer Rep', email: 'dave@boisehomes.com' }],
    notes: 'Delivered ahead of schedule. All units sold. Great reference project.',
    photos: [],
    tags: ['starter', 'completed'],
    priority: 'low',
    healthStatus: 'on-track',
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-11-15T00:00:00Z',
    history: [],
  },
  {
    id: '8',
    name: 'Colorado Springs 20-Unit',
    location: { city: 'Colorado Springs', state: 'CO', lat: 38.8339, lng: -104.8214 },
    stage: 'production',
    unitCount: 20,
    estimatedValue: 3800000,
    startDate: '2025-10-15',
    estimatedCompletion: '2026-07-01',
    contacts: [{ name: 'Rachel Torres', role: 'Site Super', email: 'rachel@fwbuilds.com' }],
    notes: 'Module assembly 60% complete. On track for July delivery.',
    photos: [],
    tags: ['multi-family'],
    priority: 'high',
    healthStatus: 'on-track',
    createdAt: '2025-07-01T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
    history: [],
  },
];
